export const CHAT_OPENED = 'CHAT_OPENED';
export const CHAT_CLOSED = 'CHAT_CLOSED';
export const CHAT_MESSAGES_FETCHED = 'CHAT_MESSAGES_FETCHED';
export const CHAT_MESSAGE_POSTED = 'CHAT_MESSAGE_POSTED';
export const HTTP_ERROR = 'HTTP_ERROR';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';